run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - prealloc
    - misspell
    - lll
    - unparam
    - nakedret
    - gocritic
    - gochecknoinits
    - gochecknoglobals

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
    
    # Exclude main.go from gochecknoglobals and formatting (if it's a simple main)
    - path: main\.go
      linters:
        - gochecknoglobals
        - gofmt
    
    # Exclude cmd/ files from gochecknoglobals - CLI commands legitimately use global variables
    - path: cmd/
      linters:
        - gochecknoglobals
        - gochecknoinits  # init functions are legitimate in CLI commands
    
    # Exclude constants that are defined for completeness but may not be used yet
    - source: "const.*authMethod.*"
      linters:
        - unused
    
    # Exclude performance monitoring constants that may be used in different contexts
    - source: "const.*perfMonitoring.*"
      linters:
        - goconst
    
    # Exclude integer overflow in performance monitoring - it's intentional conversion
    - path: internal/tts/performance\.go
      text: "G115.*integer overflow conversion"
      linters:
        - gosec
    
    # Exclude goconst for short, context-specific strings that shouldn't be constants
    - text: "string.*has 2 occurrences.*make it a constant"
      linters:
        - goconst
    
    # Exclude already existing constants from goconst suggestions
    - text: "string .* has 2 occurrences, but such constant .* already exists"
      linters:
        - goconst
    
    # Exclude performance monitoring disabled message
    - text: "Performance monitoring is disabled.*has 2 occurrences"
      linters:
        - goconst
    
    # Exclude exitAfterDefer in login command - intentional pattern for CLI error handling
    - path: cmd/login\.go
      text: "exitAfterDefer: os.Exit will exit"
      linters:
        - gocritic
    
    # Exclude fieldalignment - performance impact is minimal and alignment changes reduce readability
    - text: "fieldalignment: struct.*could be.*"
      linters:
        - govet
    
    # Exclude ineffectual assignments that are intentional
    - path: test/integration_test\.go
      text: "ineffectual assignment to cmd"
      linters:
        - ineffassign
    
    - path: internal/tts/client\.go
      text: "ineffectual assignment to audioEncoding"
      linters:
        - ineffassign
    
    # Exclude append result assignment issues in audio.go - these are platform-specific and acceptable
    - path: internal/player/audio\.go
      text: "appendAssign: append result not assigned to the same slice"
      linters:
        - gocritic
    
    # Exclude copy locks warning in performance.go - this is intentionally handled correctly
    - path: internal/tts/performance\.go
      text: "copylocks: literal copies lock value"
      linters:
        - govet
    
    # Exclude long lines that are acceptable (error messages, URLs, etc.)
    - text: "The line is.*characters long.*exceeds.*120 characters"
      linters:
        - lll
    
    # Exclude unused parameter in internal/tts/client.go - kept for future use
    - path: internal/tts/client\.go
      text: "`createOptimizedClient` - `config` is unused"
      linters:
        - unparam
    
    # Exclude unused auth constants - kept for completeness and future use
    - path: internal/config/config\.go
      text: "const.*authMethod.*is unused"
      linters:
        - unused
    
    # Exclude append result assignment in test files - acceptable in tests
    - path: .*_test\.go
      text: "appendAssign: append result not assigned to the same slice"
      linters:
        - gocritic
    
    # Exclude staticcheck warnings about unused values in tests - often intentional
    - path: test/integration_test\.go
      text: "SA4006: this value.*is never used"
      linters:
        - staticcheck