run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - prealloc
    - misspell
    - lll
    - unparam
    - nakedret
    - gocritic
    - gochecknoinits
    - gochecknoglobals

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
    
    # Exclude main.go from gochecknoglobals
    - path: main\.go
      linters:
        - gochecknoglobals